version: '3.7'
services:
  fms-c:
    image: centos-fms-c-19_2:latest
    container_name: fms-c
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./databases/:/opt/FileMaker/FileMaker Server/Data/Databases/
      # - ./build/:/root/build/
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
    ports:
      - 80:80
      - 443:443
      - 2399:2399
      - 5003:5003
      - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.11
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    restart: "no"
    stdin_open: true
    tty: true
    # command: bash

  fms:
    image: centos-fms-19_2:latest
    container_name: fms
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./databases/:/opt/FileMaker/FileMaker Server/Data/Databases/
      # - ./build/:/root/build/
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
    ports:
      - 80:80
      - 443:443
      - 2399:2399
      - 5003:5003
      - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.11
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    restart: "no"
    stdin_open: true
    tty: true
    # command: bash

  d-fms2.fmgarage.com:
    # image: centos-sysd-fms:2020-11-11
    image: centos-fms-19_2:2021-03-25
    container_name: fms2
    hostname: d-fms2.fmgarage.com
    depends_on:
      - reverse
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # - ./data/:/opt/FileMaker/FileMaker Server/Data/Databases/
      # - ./build/:/root/build/
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    security_opt:
      - seccomp:unconfined
    user: root
    environment:
      - container=docker
    cap_add:
      - SYS_ADMIN
    # ports:
    #   - 80:80
    #   - 443:443
    #   - 2399:2399
    #   - 5003:5003
    #   - 16000-16002:16000-16002
    networks:
      fms:
        ipv4_address: 172.20.0.12
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "5"
    # init: true
    # privileged: true
    restart: "no"
    stdin_open: true
    tty: true
    # command: bash

  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 5003:5003
      - 16000:16000
    networks:
      fms:
        ipv4_address: 172.20.0.50
    volumes:
      - ./nginx_config:/etc/nginx
      - ./nginx_cert/:/etc/ssl/fmg/
    # command: bash

networks:
    fms:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.20.0.0/16
